format_version: 10
pipelines:
  My-New-Pipeline:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-b8df1cb:
        git: https://github.com/NRAJKU/NewTest.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - Test-and-Run:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          run-and-test:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - hello
                command: echo
                run_if: passed
  My-New-Pipeline_2:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      My-New-Pipeline:
        ignore_for_scheduling: false
        pipeline: My-New-Pipeline
        stage: Test-and-Run
    stages:
    - Test-and-Run:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          run-and-test:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - hello
                command: echo
                run_if: passed
            - exec:
                arguments:
                - hello
                command: echo
                run_if: passed